# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry config http-basic.home $PYPI_USER $PYPI_PASSWORD
  - poetry install -v
  - export PYTHONPATH="$(pwd)/src:$(pwd)/src/horizons_web_service:$PYTHONPATH"

stages:
  - Static Analysis
  - Tests
  - Build Prep
  - Build
  - Deploy

Pylint:
  stage: Static Analysis
  retry: 1
  script:
    - pylint -E -d C0301 src/horizons_web_service tests

Black:
  stage: Static Analysis
  retry: 1
  script:
    - python -m black . --check --verbose

Unit:
  stage: Tests
  retry: 1
  script:
    - pytest -v ./tests/unit

Functional:
  stage: Tests
  retry: 1
  script:
    - pytest -v ./tests/functional

Build_Prep:
  stage: Build Prep
  retry: 1
  only:
    - main
  before_script:
    - pip install poetry
  script:
    - HORIZONS_API_VERSION=$(poetry version -s)
    - echo "$(poetry version -s)" > VERSION
  artifacts:
    paths:
      - VERSION

Build:
  stage: Build
  retry: 1
  only:
    - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script: []
  dependencies:
    - Build_Prep
  script:
    - HORIZONS_VERSION=$(cat VERSION)
    - mkdir -p /kaniko/.docker
    - >-
      /kaniko/executor
      --insecure
      --skip-tls-verify
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/src/docker/Dockerfile"
      --destination "levan.home:5000/horizons-api:${HORIZONS_VERSION}"
      --build-arg PYPI_USER=$PYPI_USER
      --build-arg PYPI_PASSWORD=$PYPI_PASSWORD

Deploy:
  stage: Deploy
  retry: 1
  dependencies:
    - Build_Prep
  only:
    - main
  image: alpine/helm:3.8.1
  before_script: []
  script:
    - HORIZONS_VERSION=$(cat VERSION)
    - helm upgrade horizons-api ./horizons-api --install --values=./horizons-api/values.yaml --namespace horizons --set image.tag=$HORIZONS_VERSION
