# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"


# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install poetry==1.1.15
  - poetry config virtualenvs.create false
  - poetry config http-basic.home $PYPI_USER $PYPI_PASSWORD
  - poetry install -v
  - export PYTHONPATH="$(pwd)/src:$(pwd)/src/horizons_web_service:$PYTHONPATH"

stages:
  - Static Analysis
  - Test Build
  - Test Deploy
  - Tests
  - Test Cleanup
  - Build Prep
  - Build
  - Deploy

Pylint:
  stage: Static Analysis
  retry: 1
  script:
    - pylint -E -d C0301 src/horizons_web_service tests

Black:
  stage: Static Analysis
  retry: 1
  script:
    - python -m black . --check --verbose

Test-Build:
  stage: Test Build
  retry: 1
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script: []
  script:
    - mkdir -p /kaniko/.docker
    - >-
      /kaniko/executor
      --insecure
      --skip-tls-verify
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/src/docker/Dockerfile"
      --destination "levan.home:5000/horizons-api:${CI_COMMIT_SHORT_SHA}"
      --build-arg PYPI_USER=$PYPI_USER
      --build-arg PYPI_PASSWORD=$PYPI_PASSWORD

Test-Deploy:
  stage: Test Deploy
  retry: 1
  image: alpine/helm:3.8.1
  before_script: []
  script:
    - HORIZONS_VERSION=$CI_COMMIT_BRANCH
    - >-
      helm upgrade --install horizons-api-"$CI_COMMIT_SHORT_SHA"
      ./horizons-api
      --values=./horizons-api/values.yaml
      --namespace horizons
      --set image.tag="$CI_COMMIT_SHORT_SHA"
      --set fullnameOverride=horizons-api-"$CI_COMMIT_SHORT_SHA"
      --set ingress.middleware.prefix="/api/$CI_COMMIT_SHORT_SHA"
      --set ingress.hosts[0].paths[0].path="api/$CI_COMMIT_SHORT_SHA"
      --set ingress."annotations\.traefik\.ingress\.kubernetes\.io/router.middlewares"="horizons-horizons-api-$CI_COMMIT_SHORT_SHA-middleware@kubernetescrd"

Unit:
  stage: Tests
  retry: 1
  script:
    - pytest -v ./tests/unit

Functional:
  stage: Tests
  retry: 1
  script:
    - pytest -v ./tests/functional

E2E:
  stage: Tests
  dependencies:
    - Test-Build
    - Test-Deploy
  retry: 1
  script:
    - export HORIZONS_API_URL="http://levan.home/api/$CI_COMMIT_SHORT_SHA"
    - ./wait_for_endpoint.sh
    - pytest -v ./tests/e2e
  allow_failure: true

Docker_Cleanup:
  stage: Test Cleanup
  dependencies:
    - Test-Deploy
  retry: 1
  before_script: [ ]
  script:
    - ./delete_docker_image.sh

Helm_Cleanup:
  stage: Test Cleanup
  dependencies:
    - Test-Deploy
  retry: 1
  image: alpine/helm:3.8.1
  before_script: [ ]
  script:
    - helm uninstall horizons-api-"$CI_COMMIT_SHORT_SHA"

Build_Prep:
  stage: Build Prep
  retry: 1
  only:
    - main
  before_script:
    - pip install poetry
  script:
    - HORIZONS_API_VERSION=$(poetry version -s)
    - echo "$(poetry version -s)" > VERSION
  artifacts:
    paths:
      - VERSION

Build:
  stage: Build
  retry: 1
  only:
    - main
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script: []
  dependencies:
    - Build_Prep
  script:
    - HORIZONS_VERSION=$(cat VERSION)
    - mkdir -p /kaniko/.docker
    - >-
      /kaniko/executor
      --insecure
      --skip-tls-verify
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/src/docker/Dockerfile"
      --destination "levan.home:5000/horizons-api:${HORIZONS_VERSION}"
      --build-arg PYPI_USER=$PYPI_USER
      --build-arg PYPI_PASSWORD=$PYPI_PASSWORD

Deploy:
  stage: Deploy
  retry: 1
  dependencies:
    - Build_Prep
  only:
    - main
  image: alpine/helm:3.8.1
  before_script: []
  script:
    - HORIZONS_VERSION=$(cat VERSION)
    - helm upgrade --install horizons-api ./horizons-api --values=./horizons-api/values.yaml --namespace horizons --set image.tag=$HORIZONS_VERSION
